[package]
name = "small_rngs"
version = "0.0.1"
authors = ["pitdicker"]

[features]
nightly = ["i128_support"]
i128_support = ["rand_core/i128_support"]

[dependencies]
rand = { git = "https://github.com/dhardy/rand" }
rand_core = { git = "https://github.com/dhardy/rand" }
